name: Remove all AWS resources created from this project
on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
  LAMBDA_PATH: ../predict-stocks/src/predict_lambda/"

jobs:
  remove-infra:
    if: contains('["TimBeckerAachen"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set lambda path in vars file
        working-directory: 'infrastructure'
        run: |
          sed -i 's/replace_lambda_path/${{ env.LAMBDA_PATH }}lambda_function.zip/g' vars/prod.tfvars
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::411847045573:role/github-role-stock-project
          role-session-name: predict-stocks-deployment
          aws-region: "eu-west-1"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: TF init
        id: tf-init
        working-directory: 'infrastructure'
        run: |
          terraform init -backend-config="key=predict-stocks-prod.tfstate" -reconfigure
      - name: TF destroy
        id: tf-destroy
        working-directory: 'infrastructure'
        run: |
          terraform destroy -auto-approve -var-file=vars/prod.tfvars